# Generated by Django 5.2.3 on 2025-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
